package team.abnormals.neutronia.client.entity.render.model.model;

import com.mojang.blaze3d.platform.GlStateManager;
import net.minecraft.client.model.Cuboid;
import net.minecraft.client.render.entity.model.EntityModel;
import net.minecraft.entity.Entity;

/**
 * wydra.tcn - TechneToTabulaImporter
 * Created using Tabula 7.0.0
 */
public class ModelWydra extends EntityModel {
    public Cuboid body;
    public Cuboid neck;
    public Cuboid head;
    public Cuboid mouth;
    public Cuboid tail;
    public Cuboid tipoftail;
    public Cuboid Shoulder;
    public Cuboid Shoulder_1;
    public Cuboid Shoulder_2;
    public Cuboid Shoulder_3;
    public Cuboid Shoulder_4;
    public Cuboid Shoulder_5;
    public Cuboid paw;
    public Cuboid paw_1;
    public Cuboid paw_2;
    public Cuboid paw_3;
    public Cuboid thigh;
    public Cuboid thigh_1;

    public ModelWydra() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.Shoulder = new Cuboid(this, 59, 0);
        this.Shoulder.setRotationPoint(-4.0F, 16.0F, -1.0F);
        this.Shoulder.addBox(0.0F, 0.0F, 0.0F, 4, 5, 3, 0.0F);
        this.setRotateAngle(Shoulder, 0.3867998719215393F, -0.0F, 0.0F);
        this.paw = new Cuboid(this, 75, 0);
        this.paw.setRotationPoint(-4.0F, 23.0F, -3.0F);
        this.paw.addBox(0.0F, 0.0F, 0.0F, 4, 1, 4, 0.0F);
        this.thigh = new Cuboid(this, 0, 91);
        this.thigh.setRotationPoint(-3.866666555404663F, 12.300000190734863F, 12.0F);
        this.thigh.addBox(0.0F, 0.0F, 0.0F, 3, 7, 5, 0.0F);
        this.setRotateAngle(thigh, -0.3346075117588043F, -0.0F, 0.0F);
        this.body = new Cuboid(this, 0, 16);
        this.body.setRotationPoint(-2.0F, 11.0F, 0.0F);
        this.body.addBox(0.0F, 0.0F, 0.0F, 11, 8, 18, 0.0F);
        this.paw_1 = new Cuboid(this, 75, 0);
        this.paw_1.setRotationPoint(7.0F, 23.0F, -3.0F);
        this.paw_1.addBox(0.0F, 0.0F, 0.0F, 4, 1, 4, 0.0F);
        this.Shoulder_1 = new Cuboid(this, 59, 0);
        this.Shoulder_1.setRotationPoint(4.0F, 16.0F, -2.0F);
        this.Shoulder_1.addBox(3.0F, 0.0F, 1.0F, 4, 5, 3, 0.0F);
        this.setRotateAngle(Shoulder_1, 0.38680213689804077F, -0.0F, 0.0F);
        this.mouth = new Cuboid(this, 0, 42);
        this.mouth.setRotationPoint(2.0F, 12.0F, -15.0F);
        this.mouth.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2, 0.0F);
        this.paw_2 = new Cuboid(this, 75, 0);
        this.paw_2.setRotationPoint(-3.0F, 13.0F, 12.0F);
        this.paw_2.addBox(-1.0F, 10.0F, 0.0F, 3, 1, 4, 0.0F);
        this.Shoulder_3 = new Cuboid(this, 59, 0);
        this.Shoulder_3.setRotationPoint(-4.0F, 18.0F, 0.5F);
        this.Shoulder_3.addBox(0.0F, 0.0F, 0.0F, 4, 5, 3, 0.0F);
        this.setRotateAngle(Shoulder_3, -0.31959149241447454F, -0.0F, 0.0F);
        this.thigh_1 = new Cuboid(this, 0, 91);
        this.thigh_1.setRotationPoint(7.900000095367432F, 12.300000190734863F, 14.0F);
        this.thigh_1.addBox(0.0F, 0.0F, 0.0F, 3, 7, 5, 0.0F);
        this.setRotateAngle(thigh_1, -0.3346075117588043F, -0.0F, 0.0F);
        this.Shoulder_2 = new Cuboid(this, 59, 0);
        this.Shoulder_2.setRotationPoint(7.0F, 18.0F, 0.46666666865348816F);
        this.Shoulder_2.addBox(0.0F, 0.0F, 0.0F, 4, 5, 3, 0.0F);
        this.setRotateAngle(Shoulder_2, -0.31959149241447454F, -0.0F, 0.0F);
        this.paw_3 = new Cuboid(this, 75, 0);
        this.paw_3.setRotationPoint(8.0F, 23.0F, 12.0F);
        this.paw_3.addBox(0.0F, 0.0F, 0.0F, 3, 1, 4, 0.0F);
        this.head = new Cuboid(this, 0, 0);
        this.head.setRotationPoint(1.0F, 10.0F, -14.0F);
        this.head.addBox(0.0F, 0.0F, 0.0F, 5, 5, 8, 0.0F);
        this.Shoulder_5 = new Cuboid(this, 59, 0);
        this.Shoulder_5.setRotationPoint(-4.0F, 19.0F, 12.0F);
        this.Shoulder_5.addBox(0.0F, 0.0F, 0.0F, 3, 5, 3, 0.0F);
        this.setRotateAngle(Shoulder_5, 0.38680213689804077F, -0.0F, 0.0F);
        this.tail = new Cuboid(this, 0, 51);
        this.tail.setRotationPoint(0.0F, 12.0F, 17.0F);
        this.tail.addBox(0.0F, 0.0F, 0.0F, 7, 5, 15, 0.0F);
        this.setRotateAngle(tail, -0.2602502703666687F, -0.0F, 0.0F);
        this.Shoulder_4 = new Cuboid(this, 59, 0);
        this.Shoulder_4.setRotationPoint(8.0F, 19.0F, 13.0F);
        this.Shoulder_4.addBox(0.0F, 0.0F, 0.0F, 3, 5, 3, 0.0F);
        this.setRotateAngle(Shoulder_4, 0.38680213689804077F, -0.0F, 0.0F);
        this.neck = new Cuboid(this, 26, 0);
        this.neck.setRotationPoint(0.0F, 9.0F, -6.0F);
        this.neck.addBox(0.0F, 0.0F, 0.0F, 7, 7, 9, 0.0F);
        this.setRotateAngle(neck, -0.3346075117588043F, -0.0F, 0.0F);
        this.tipoftail = new Cuboid(this, 0, 75);
        this.tipoftail.setRotationPoint(1.0F, 16.0F, 31.0F);
        this.tipoftail.addBox(0.0F, 0.0F, 0.0F, 5, 4, 7, 0.0F);
        this.setRotateAngle(tipoftail, -0.4461433291435241F, -0.0F, 0.0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.Shoulder.x, this.Shoulder.y, this.Shoulder.z);
        GlStateManager.translatef(this.Shoulder.rotationPointX * f5, this.Shoulder.rotationPointY * f5, this.Shoulder.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.Shoulder.x, -this.Shoulder.y, -this.Shoulder.z);
        GlStateManager.translatef(-this.Shoulder.rotationPointX * f5, -this.Shoulder.rotationPointY * f5, -this.Shoulder.rotationPointZ * f5);
        this.Shoulder.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.paw.x, this.paw.y, this.paw.z);
        GlStateManager.translatef(this.paw.rotationPointX * f5, this.paw.rotationPointY * f5, this.paw.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.paw.x, -this.paw.y, -this.paw.z);
        GlStateManager.translatef(-this.paw.rotationPointX * f5, -this.paw.rotationPointY * f5, -this.paw.rotationPointZ * f5);
        this.paw.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.thigh.x, this.thigh.y, this.thigh.z);
        GlStateManager.translatef(this.thigh.rotationPointX * f5, this.thigh.rotationPointY * f5, this.thigh.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.thigh.x, -this.thigh.y, -this.thigh.z);
        GlStateManager.translatef(-this.thigh.rotationPointX * f5, -this.thigh.rotationPointY * f5, -this.thigh.rotationPointZ * f5);
        this.thigh.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.body.x, this.body.y, this.body.z);
        GlStateManager.translatef(this.body.rotationPointX * f5, this.body.rotationPointY * f5, this.body.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.body.x, -this.body.y, -this.body.z);
        GlStateManager.translatef(-this.body.rotationPointX * f5, -this.body.rotationPointY * f5, -this.body.rotationPointZ * f5);
        this.body.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.paw_1.x, this.paw_1.y, this.paw_1.z);
        GlStateManager.translatef(this.paw_1.rotationPointX * f5, this.paw_1.rotationPointY * f5, this.paw_1.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.paw_1.x, -this.paw_1.y, -this.paw_1.z);
        GlStateManager.translatef(-this.paw_1.rotationPointX * f5, -this.paw_1.rotationPointY * f5, -this.paw_1.rotationPointZ * f5);
        this.paw_1.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.Shoulder_1.x, this.Shoulder_1.y, this.Shoulder_1.z);
        GlStateManager.translatef(this.Shoulder_1.rotationPointX * f5, this.Shoulder_1.rotationPointY * f5, this.Shoulder_1.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.Shoulder_1.x, -this.Shoulder_1.y, -this.Shoulder_1.z);
        GlStateManager.translatef(-this.Shoulder_1.rotationPointX * f5, -this.Shoulder_1.rotationPointY * f5, -this.Shoulder_1.rotationPointZ * f5);
        this.Shoulder_1.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.mouth.x, this.mouth.y, this.mouth.z);
        GlStateManager.translatef(this.mouth.rotationPointX * f5, this.mouth.rotationPointY * f5, this.mouth.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.mouth.x, -this.mouth.y, -this.mouth.z);
        GlStateManager.translatef(-this.mouth.rotationPointX * f5, -this.mouth.rotationPointY * f5, -this.mouth.rotationPointZ * f5);
        this.mouth.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.paw_2.x, this.paw_2.y, this.paw_2.z);
        GlStateManager.translatef(this.paw_2.rotationPointX * f5, this.paw_2.rotationPointY * f5, this.paw_2.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.paw_2.x, -this.paw_2.y, -this.paw_2.z);
        GlStateManager.translatef(-this.paw_2.rotationPointX * f5, -this.paw_2.rotationPointY * f5, -this.paw_2.rotationPointZ * f5);
        this.paw_2.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.Shoulder_3.x, this.Shoulder_3.y, this.Shoulder_3.z);
        GlStateManager.translatef(this.Shoulder_3.rotationPointX * f5, this.Shoulder_3.rotationPointY * f5, this.Shoulder_3.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.Shoulder_3.x, -this.Shoulder_3.y, -this.Shoulder_3.z);
        GlStateManager.translatef(-this.Shoulder_3.rotationPointX * f5, -this.Shoulder_3.rotationPointY * f5, -this.Shoulder_3.rotationPointZ * f5);
        this.Shoulder_3.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.thigh_1.x, this.thigh_1.y, this.thigh_1.z);
        GlStateManager.translatef(this.thigh_1.rotationPointX * f5, this.thigh_1.rotationPointY * f5, this.thigh_1.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.thigh_1.x, -this.thigh_1.y, -this.thigh_1.z);
        GlStateManager.translatef(-this.thigh_1.rotationPointX * f5, -this.thigh_1.rotationPointY * f5, -this.thigh_1.rotationPointZ * f5);
        this.thigh_1.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.Shoulder_2.x, this.Shoulder_2.y, this.Shoulder_2.z);
        GlStateManager.translatef(this.Shoulder_2.rotationPointX * f5, this.Shoulder_2.rotationPointY * f5, this.Shoulder_2.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.Shoulder_2.x, -this.Shoulder_2.y, -this.Shoulder_2.z);
        GlStateManager.translatef(-this.Shoulder_2.rotationPointX * f5, -this.Shoulder_2.rotationPointY * f5, -this.Shoulder_2.rotationPointZ * f5);
        this.Shoulder_2.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.paw_3.x, this.paw_3.y, this.paw_3.z);
        GlStateManager.translatef(this.paw_3.rotationPointX * f5, this.paw_3.rotationPointY * f5, this.paw_3.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.paw_3.x, -this.paw_3.y, -this.paw_3.z);
        GlStateManager.translatef(-this.paw_3.rotationPointX * f5, -this.paw_3.rotationPointY * f5, -this.paw_3.rotationPointZ * f5);
        this.paw_3.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.head.x, this.head.y, this.head.z);
        GlStateManager.translatef(this.head.rotationPointX * f5, this.head.rotationPointY * f5, this.head.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.head.x, -this.head.y, -this.head.z);
        GlStateManager.translatef(-this.head.rotationPointX * f5, -this.head.rotationPointY * f5, -this.head.rotationPointZ * f5);
        this.head.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.Shoulder_5.x, this.Shoulder_5.y, this.Shoulder_5.z);
        GlStateManager.translatef(this.Shoulder_5.rotationPointX * f5, this.Shoulder_5.rotationPointY * f5, this.Shoulder_5.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.Shoulder_5.x, -this.Shoulder_5.y, -this.Shoulder_5.z);
        GlStateManager.translatef(-this.Shoulder_5.rotationPointX * f5, -this.Shoulder_5.rotationPointY * f5, -this.Shoulder_5.rotationPointZ * f5);
        this.Shoulder_5.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.tail.x, this.tail.y, this.tail.z);
        GlStateManager.translatef(this.tail.rotationPointX * f5, this.tail.rotationPointY * f5, this.tail.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.tail.x, -this.tail.y, -this.tail.z);
        GlStateManager.translatef(-this.tail.rotationPointX * f5, -this.tail.rotationPointY * f5, -this.tail.rotationPointZ * f5);
        this.tail.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.Shoulder_4.x, this.Shoulder_4.y, this.Shoulder_4.z);
        GlStateManager.translatef(this.Shoulder_4.rotationPointX * f5, this.Shoulder_4.rotationPointY * f5, this.Shoulder_4.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.Shoulder_4.x, -this.Shoulder_4.y, -this.Shoulder_4.z);
        GlStateManager.translatef(-this.Shoulder_4.rotationPointX * f5, -this.Shoulder_4.rotationPointY * f5, -this.Shoulder_4.rotationPointZ * f5);
        this.Shoulder_4.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.neck.x, this.neck.y, this.neck.z);
        GlStateManager.translatef(this.neck.rotationPointX * f5, this.neck.rotationPointY * f5, this.neck.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.neck.x, -this.neck.y, -this.neck.z);
        GlStateManager.translatef(-this.neck.rotationPointX * f5, -this.neck.rotationPointY * f5, -this.neck.rotationPointZ * f5);
        this.neck.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translatef(this.tipoftail.x, this.tipoftail.y, this.tipoftail.z);
        GlStateManager.translatef(this.tipoftail.rotationPointX * f5, this.tipoftail.rotationPointY * f5, this.tipoftail.rotationPointZ * f5);
        GlStateManager.scaled(0.8999999761581421D, 1.0D, 1.0D);
        GlStateManager.translatef(-this.tipoftail.x, -this.tipoftail.y, -this.tipoftail.z);
        GlStateManager.translatef(-this.tipoftail.rotationPointX * f5, -this.tipoftail.rotationPointY * f5, -this.tipoftail.rotationPointZ * f5);
        this.tipoftail.render(f5);
        GlStateManager.popMatrix();
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(Cuboid Cuboid, float x, float y, float z) {
        Cuboid.rotationPointX = x;
        Cuboid.rotationPointY = y;
        Cuboid.rotationPointZ = z;
    }
}
